# # # # # # # # # # # # # # 
# 1. datasets
# # # # # # # # # # # # # # 
dataset: # Required.
  type: cityscapes_semi
  train:
    data_root: ./data/cityscapes
    data_list: ./data/splits/cityscapes/372/labeled.txt
    batch_size: 2
    flip: True
    rand_resize: [0.5, 2.0]
    resize_base_size: [1024, 2048]
    strong_aug:
      num_augs: 2
    hardness_aware:
      flag_using_v1: True
      flag_hardness_weighted_loss: True
      flag_cal_iou_weighted: True
      flag_cal_iou_ignore_bg: True 
      flag_cmix_trigger_by_hard: True
      flag_augs_mixup_by_hard: True
      flag_mapping_random: False
      flag_mapping_gaussian: False 
    crop:
      type: rand
      size: [769, 769]
  val:
    data_root: ./data/cityscapes
    data_list: ./data/splits/cityscapes/val.txt
    batch_size: 2
    crop:
      size: [769, 769] # crop image with HxW size
  n_sup: 372
  workers: 4
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  ignore_label: 255

# # # # # # # # # # # # # # 
# 2. training params
# # # # # # # # # # # # # # 
trainer: # Required.
  epochs: 240
  sup_only_epoch: 0 # 1, 2, -1
  optimizer:
    type: SGD
    kwargs:
      lr: 0.01 # 4GPUs
      momentum: 0.9
      weight_decay: 0.0005
  lr_scheduler:
    mode: poly
    kwargs:
      power: 0.9
  # # # # # # # # # # # # # # 
  # unsupervised loss
  # # # # # # # # # # # # # #
  unsupervised:
    flag_ema_pseudo: True  # delete keep true all the way
    threshold: 0.7   # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ params1: 0.7, 0.75, 0.8, 0.85, 0.9, 0.95
    use_cutmix: True
    use_cutmix_beta: False
    use_cutmix_range: [0.1, 0.9]
    use_cutmix_trigger_prob: 0.5
    loss_weight: 3.0  # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ params2: 0.7, 1.0, 1.5, 2.0, 3.0, 4.0

# # # # # # # # # # # # # # 
# 3. output files, and loss
# # # # # # # # # # # # # # 
saver:
  snapshot_dir: checkpoints
  pretrain: ''
  use_tb: False

criterion:
  type: ohem
  kwargs:
    thresh: 0.7
    min_kept: 100000

# # # # # # # # # # # # # # 
# 4. models
# # # # # # # # # # # # # # 
net: # Required.
  num_classes: 19
  sync_bn: True
  ema_decay: 0.996
  aux_loss:
    aux_plane: 1024
    loss_weight: 0.4
  encoder:
    # type: imas.models.resnet.resnet101
    # pretrain: ./pretrained/resnet101.pth
    type: imas.models.resnet.resnet50
    pretrain: ./pretrained/resnet50.pth
    kwargs:
      multi_grid: True
      # multi_grid: False
      zero_init_residual: True
      fpn: True
      replace_stride_with_dilation: [False, True, True]  #layer0...1 is fixed, layer2...4
      # replace_stride_with_dilation: [False, False, True]  #layer0...1 is fixed, layer2...4
  decoder:
    type: imas.models.decoder.dec_deeplabv3_plus
    kwargs:
      rep_head: False
      inner_planes: 256
      low_conv_planes: 48 # 256
      dilations: [12, 24, 36]
      # dilations: [6, 12, 18]
